export const recommendations = [
    {
        id: `1`,
        image: './basketball_orange.png',
        title: `М'яч баскетбольний Nike Everyday Play...`,
        oldPrice: 1059,
        price: 877,
    },
    {   
        id: `2`,
        image: './puzzle.png',
        title: `Пазли тришарові Interdruk Secret Garden`,
        oldPrice: 889,
        price: 695,
    },
    {   
        id: `3`,
        image: './lamp.png',
        title: `Настільна лампа RZTK Pixar Lamp E27 Black`,
        oldPrice: 795,
        price: 594,
    },
    {   
        id: `4`,
        image: './shampoo.png',
        title: `Шампунь Doliva (Olivenol) 200 мл`,
        oldPrice: 340,
        price: 249,
    },
    {   
        id: `5`,
        image: './paper.png',
        title: `Папір для нотаток Axent з липким шаром`,
        oldPrice: 164,
        price: 136,
    },
    {   
        id: `6`,
        image: './shv-machine.png',
        title: `Міні швейна машинка 4.8W UTM Sewing`,
        oldPrice: 624,
        price: 387,
    },
    {   
        id: `7`,
        image: './dog_food.png',
        title: `Упаковка ласощів для собак Half&Half `,
        oldPrice: 132,
        price: 81,
    },
]

export const offers = [
    {
        id: `1`,
        hoverImage: './popmart_card.png',
        image: './test_img.png',
        description:
            'М`яка іграшка-сюрприз Big into Energy Art The Monsters - стильний аксесуар для рюкзака, сумки або як подарунок!  Ця іграшка стане чудовим...',
        title: `Іграшка-сюрприз Pop Mart Плюшевый брелок Mart Big...`,
        rating: 3,
        reviews: 1,
        oldPrice: 999,
        price: 799,
    },
    {
        id: `2`,
        hoverImage: './cleaner_2.png',
        image: './cleaner_robot.png',
        description:
            'Робот для миття вікон DYXON MEGAWASHER 1000, найкраще рішення для постійного догляду за вікнами, скляними та дзеркальними поверхнями...',
        title: `Робот для миття вікон DYXON MEGAWASHER 1000 White`,
        rating: 4,
        reviews: 4,
        oldPrice: 9839,
        price: 7689,
    },
    {
        id: `3`,
        hoverImage: './monlasa_cockies_2.png',
        image: './monlasa_coockies.png',
        description:
            'Ніжне та запашне печиво з неймовірним поєднанням смаків кокоса, мигдалю та журавлини. Виготовлене з інгредієнтів що не містять глютен...',
        title: `Печиво MonLasa кокосово-мигдальне безглютенове 120 г `,
        rating: 5,
        reviews: 71,
        oldPrice: 137,
        price: 99,
    },
    {
        id: `4`,
        hoverImage: './coockies_2.png',
        image: './coockies.png',
        description:
            'Справжній гастрономічний шедевр, який поєднує в собі хрусткі вафлі і ніжний молочний шоколад. Ці милі рибки виготовлені з якісних інгредієнтів і...',
        title: `Вафельне печиво рибки з молочним шоколадом Meito 16г `,
        rating: 4,
        reviews: 1,
        oldPrice: 137,
        price: 127,        
    },
    {
        id: `5`,
        hoverImage: './watches_2.png',
        image: './watches.png',
        description:
            'Ласкаво просимо в нову еру турботи про здоров`я Galaxy AI. Заряджайтеся енергією протягом дня з новим 3-нм процесором. Точно орієнтуйтеся за...',
        title: `Смарт-годинник Samsung Galaxy Watch 7 40mm Cream`,
        rating: 4,
        reviews: 34,
        oldPrice: 13499,
        price: 9999,
    },
    {
        id: `6`,
        hoverImage: './circle_armchair_2.png',
        image: './circle_armchair.png',
        description:
            'Веселе та безпечне дозвілля для всіх любителів водних розваг! Підходить для використання на пляжі, морі, будинку, басейні, природі та ін.',
        title: `Надувне коло-крісло Intex 56825, "Aqua River Run"`,
        rating: 0,
        reviews: 0,
        oldPrice: 1599,
        price: 1099,        
    },
    {
        id: `7`,
        hoverImage: './pets_backpack_2.png',
        image: './pets_backpack.png',
        description:
            'ТРАНСПОРТЕР ДЛЯ КОТІВ/СОБАК - ПРОЗОРА ЧОРНА СУМКА: Міцна конструкція, Дихаюча сітка Ергономічний дизайн, Легко підтримувати в...',
        title: `Переноска-рюкзак для тварин 35 см х 42 см Чорний`,
        rating: 4,
        reviews: 18,
        oldPrice: 604,
        price: 507,
    },
    {
        id: `8`,
        hoverImage: './zibi_2.png',
        image: './zibi.png',
        description:
            'Веселе та безпечне дозвілля для всіх любителів водних розваг! Підходить для використання на пляжі, морі, будинку, басейні, природі та ін.',
        title: `Надувне коло-крісло Intex 56825, "Aqua River Run"`,
        rating: 5,
        reviews: 2,
        oldPrice: 400,
        price: 293,        
    },
    {
        id: `9`,
        hoverImage: './ziomi_walk_2.png',
        image: './xiomi_walk.png',
        description:
            'Ви не повинні ігнорувати своє здоров`я, незалежно від того, наскільки ви зайняті. У члени з нашої команди для розробки бігової доріжки входять...',
        title: `Доріжка для ходьби Xiaomi KingSmith WalkingPad С2 White`,
        rating: 4,
        reviews: 35,
        oldPrice: 22999,
        price: 19999,
    },
    {
        id: `10`,
        hoverImage: './shoes-Boy_2.png',
        image: './shoes_boy.png',
        description:
            'Легкі, гнучкі та повітропроникні - це все про сандалі Puma Evolve Sandal. Характерний дизайн у поєднанні зі зручністю робить їх ідеальною парою...',
        title: `Дитячі сандалії для хлопчика Puma Evolve Sandal 38914701`,
        rating: 5,
        reviews: 2,
        oldPrice: 1640,
        price: 1249,        
    },
    {
        id: `11`,
        hoverImage: './ariel_color_2.png',
        image: './ariel_color.png',
        description:
            'Для прання кольорових тканин — гель Ariel Color. Він ефективний навіть на коротких циклах і за температури 30 °C.',
        title: `Гель для прання Ariel Color 4.5 л (8006540869376)`,
        rating: 4,
        reviews: 108,
        oldPrice: 1384,
        price: 699,
    },
    {
        id: `12`,
        hoverImage: './philips_2.png',
        image: './philips.png',
        description:
            'Швидкий. Зручний. Ефективний. Дає можливість розгладити складки під будь-яким кутом — вертикально та горизонтально. Відпарювання ще...',
        title: `Відпарювач PHILIPS 7000 Серії STH7060/80`,
        rating: 5,
        reviews: 80,
        oldPrice: 4599,
        price: 2894,        
    },
]